<?php

declare(strict_types=1);

namespace App\Bloggers\Support;

/**
 * Translations for the public influencer cabinet (/bloggers), en/ru/vi —
 * same shape as App\Home\I18n\Lang. Also holds the user-facing validation
 * error strings (keyed by BloggerError::$key) so the service can stay
 * language-free. EN is the fallback. t() substitutes {placeholders}.
 */
final class BloggerLang
{
    public function __construct(public readonly string $locale) {}

    /** @param array<string,string|int|float> $params */
    public function t(string $key, array $params = []): string
    {
        $v = self::DICT[$this->locale][$key] ?? self::DICT['en'][$key] ?? $key;
        if (!is_string($v)) {
            return $key;
        }
        foreach ($params as $k => $val) {
            $v = str_replace('{' . $k . '}', (string) $val, $v);
        }
        return $v;
    }

    private const DICT = [
        'en' => [
            'lang' => 'EN',
            'w.eyebrow' => 'Influencer programme',
            'w.title' => 'Bring guests —<br>earn with <i>Veranda</i>',
            'w.lead' => 'Your own promo code, cashback on every visit and an honest report in one screen. No calls, no manual spreadsheets.',
            'w.perk1.t' => 'Your personal promo code',
            'w.perk1.d' => 'A guest says it at the till and gets a discount. The visit is credited to you automatically.',
            'w.perk2.t' => 'Cashback on every bill',
            'w.perk2.d' => 'You earn a percentage of each guest’s spend. More guests — more income.',
            'w.perk3.t' => 'Fully transparent',
            'w.perk3.d' => 'Every bill, your accrued cashback and payouts — all in your cabinet. No “take our word for it”.',
            'w.limit.badge' => '★ Start — 5%',
            'w.limit.title' => 'How your percentage works',
            'w.limit.p1' => 'Right after sign-up you have <b>5%</b> — you split it yourself between the <b>guest discount</b> and <b>your cashback</b>. Enough to start earning today.',
            'w.limit.p2' => 'Want more? <a class="contact" href="/" target="_blank" rel="noopener">Get in touch</a> any way you like — we’ll agree personal terms and raise your limit. Contacts are on the site and our socials.',
            'w.have' => 'Already with us?',
            'w.google' => 'Sign in with Google',
            'w.divider' => 'new member',
            'w.reg.h' => 'Sign up',
            'w.reg.free' => 'it’s free',
            'f.name' => 'Your name',
            'f.name.ph' => 'Anna Ivanova',
            'f.email' => 'Email for Google sign-in',
            'f.email.hint' => 'You’ll use it to log into the cabinet.',
            'f.promo' => 'Promo code',
            'f.promo.hint' => 'A short word with no spaces — guests say it at the till.',
            'w.socials.h' => 'Social profiles — at least 2',
            'w.socials.hint' => 'Add at least two — that’s how we know you’re a real creator.',
            'w.social.add' => '+ Add a profile',
            'social.choose' => 'Choose a network',
            'social.val.ph' => '@handle or link',
            'social.site' => 'Website / other',
            'social.remove' => 'Remove',
            'w.reg.submit' => 'Create account',
            'w.reg.fine' => 'By signing up you join the Veranda programme. Starting limit is 5%, raise it any time by arrangement.',
            'd.who' => 'influencer cabinet',
            'd.logout' => 'Sign out',
            'd.promo.l' => 'Your promo code',
            'd.promo.sub' => 'Tell it to guests — the discount applies at the till',
            'd.period.from' => 'From',
            'd.period.to' => 'To',
            'd.period.btn' => 'Show period',
            'd.payout' => 'Due to you',
            'd.payout.meta' => 'Accrued {a} ₫ · paid out {p} ₫',
            'd.stat.checks' => 'Bills',
            'd.stat.revenue' => 'Revenue',
            'd.stat.accrued' => 'Accrued',
            'd.stat.paid' => 'Paid out',
            'd.checks.h' => 'Bills for the period',
            'd.checks.empty' => 'No bills yet — share your promo code 😉',
            'd.tbl.date' => 'Date',
            'd.tbl.sum' => 'Total ₫',
            'd.tbl.disc' => 'Discount ₫',
            'd.socials.h' => 'Your profiles',
            'd.dist.h' => 'Promo code & split',
            'd.limit.l' => 'Your limit<br>discount + cashback',
            'd.f.promo' => 'Promo code',
            'd.f.disc' => 'Guest discount, %',
            'd.f.cash' => 'Your cashback, %',
            'd.hint.tpl' => 'Total {s}% of {l}% available',
            'd.save' => 'Save',
            'd.raise.start' => 'Want more than 5%? <a href="/" target="_blank" rel="noopener">Get in touch</a> — we’ll discuss terms and raise the limit. Contacts on the site.',
            'd.raise.more' => 'Need a higher limit? <a href="/" target="_blank" rel="noopener">Message us</a> — always in touch.',
            'd.foot' => 'Cashback is calculated on revenue after discount. Payouts by arrangement.',
            'd.load.err' => 'Could not load data. Please refresh later.',
            'fl.reg.ok' => 'Done! Sign in with Google using the same address — your cabinet is ready.',
            'fl.csrf' => 'Session expired — refresh the page and try again.',
            'fl.throttle' => 'Too many attempts. Please wait a little and try again.',
            'fl.hp' => 'Could not submit. Please try later.',
            'fl.saved' => 'Changes saved.',
            'fl.save.csrf' => 'Session expired — refresh the page and save again.',
            'err.promocode_empty' => 'Promo code can’t be empty.',
            'err.promocode_space' => 'Promo code must have no spaces (it’s typed at the till).',
            'err.promocode_long' => 'Promo code is too long (max 50 characters).',
            'err.promocode_dup' => 'Promo code “{p}” is already taken.',
            'err.email_invalid' => 'Please enter a valid email.',
            'err.email_dup' => 'This email is already registered in the programme.',
            'err.name_required' => 'Please enter your name.',
            'err.min_socials' => 'Add at least 2 social profiles.',
            'err.over_limit' => 'Discount ({d}%) + cashback ({c}%) exceed the {l}% limit.',
            'err.no_blogger' => 'No influencer specified.',
            'err.not_found' => 'Influencer not found.',
            'err.generic' => 'Something went wrong. Please try later.',
        ],
        'ru' => [
            'lang' => 'RU',
            'w.eyebrow' => 'Программа для инфлюенсеров',
            'w.title' => 'Приводите гостей —<br>зарабатывайте с <i>Veranda</i>',
            'w.lead' => 'Личный промокод, кешбек с каждого визита и честный отчёт в один экран. Без созвонов и ручных таблиц.',
            'w.perk1.t' => 'Личный промокод',
            'w.perk1.d' => 'Гость называет его на кассе и получает скидку. Визит автоматически засчитывается вам.',
            'w.perk2.t' => 'Кешбек с каждого чека',
            'w.perk2.d' => 'Вы получаете процент с выручки каждого приведённого гостя. Больше гостей — больше доход.',
            'w.perk3.t' => 'Всё прозрачно',
            'w.perk3.d' => 'В кабинете виден каждый чек, накопленный кешбек и выплаты. Никаких «поверьте на слово».',
            'w.limit.badge' => '★ Старт — 5%',
            'w.limit.title' => 'Как устроен ваш процент',
            'w.limit.p1' => 'Сразу после регистрации у вас <b>5%</b> — вы сами распределяете их между <b>скидкой гостям</b> и <b>своим кешбеком</b>. Этого достаточно, чтобы начать зарабатывать уже сегодня.',
            'w.limit.p2' => 'Хотите больше? <a class="contact" href="/" target="_blank" rel="noopener">Свяжитесь с нами</a> любым удобным способом — обсудим персональные условия и поднимем ваш лимит. Контакты есть на сайте и в наших соцсетях.',
            'w.have' => 'Уже с нами?',
            'w.google' => 'Войти через Google',
            'w.divider' => 'новый участник',
            'w.reg.h' => 'Зарегистрироваться',
            'w.reg.free' => 'это бесплатно',
            'f.name' => 'Ваше имя',
            'f.name.ph' => 'Анна Иванова',
            'f.email' => 'Email для входа через Google',
            'f.email.hint' => 'На него вы будете входить в кабинет.',
            'f.promo' => 'Промокод',
            'f.promo.hint' => 'Короткое слово без пробелов — его гости называют на кассе.',
            'w.socials.h' => 'Соцсети — минимум 2',
            'w.socials.hint' => 'Добавьте минимум две — так мы убедимся, что вы реальный блогер.',
            'w.social.add' => '+ Добавить соцсеть',
            'social.choose' => 'Выберите соцсеть',
            'social.val.ph' => '@ник или ссылка',
            'social.site' => 'Сайт / другое',
            'social.remove' => 'Убрать',
            'w.reg.submit' => 'Создать аккаунт',
            'w.reg.fine' => 'Регистрируясь, вы присоединяетесь к программе Veranda. Стартовый лимит — 5%, поднять можно в любой момент по договорённости.',
            'd.who' => 'кабинет инфлюенсера',
            'd.logout' => 'Выйти',
            'd.promo.l' => 'Ваш промокод',
            'd.promo.sub' => 'Называйте его гостям — скидка применится на кассе',
            'd.period.from' => 'Начало',
            'd.period.to' => 'Конец',
            'd.period.btn' => 'Показать период',
            'd.payout' => 'К выплате',
            'd.payout.meta' => 'Накоплено {a} ₫ · выплачено {p} ₫',
            'd.stat.checks' => 'Чеки',
            'd.stat.revenue' => 'Выручка',
            'd.stat.accrued' => 'Начислено',
            'd.stat.paid' => 'Выплачено',
            'd.checks.h' => 'Чеки за период',
            'd.checks.empty' => 'Чеков пока нет — поделитесь промокодом 😉',
            'd.tbl.date' => 'Дата',
            'd.tbl.sum' => 'Сумма ₫',
            'd.tbl.disc' => 'Скидка ₫',
            'd.socials.h' => 'Ваши соцсети',
            'd.dist.h' => 'Промокод и распределение',
            'd.limit.l' => 'Ваш лимит<br>скидка + кешбек',
            'd.f.promo' => 'Промокод',
            'd.f.disc' => 'Скидка гостям, %',
            'd.f.cash' => 'Ваш кешбек, %',
            'd.hint.tpl' => 'Итого {s}% из {l}% доступных',
            'd.save' => 'Сохранить',
            'd.raise.start' => 'Хотите процент выше 5%? <a href="/" target="_blank" rel="noopener">Свяжитесь с нами</a> — обсудим условия и поднимем лимит. Контакты на сайте.',
            'd.raise.more' => 'Нужен лимит выше? <a href="/" target="_blank" rel="noopener">Напишите нам</a> — всегда на связи.',
            'd.foot' => 'Кешбек считается от выручки после скидки. Выплаты — по договорённости.',
            'd.load.err' => 'Не удалось загрузить данные. Обновите страницу позже.',
            'fl.reg.ok' => 'Готово! Войдите через Google тем же адресом — и личный кабинет ваш.',
            'fl.csrf' => 'Сессия устарела — обновите страницу и попробуйте ещё раз.',
            'fl.throttle' => 'Слишком много попыток. Подождите немного и попробуйте снова.',
            'fl.hp' => 'Не удалось отправить заявку. Попробуйте позже.',
            'fl.saved' => 'Изменения сохранены.',
            'fl.save.csrf' => 'Сессия устарела — обновите страницу и сохраните ещё раз.',
            'err.promocode_empty' => 'Промокод не может быть пустым.',
            'err.promocode_space' => 'Промокод не должен содержать пробелов (его ищут на кассе).',
            'err.promocode_long' => 'Промокод слишком длинный (макс. 50 символов).',
            'err.promocode_dup' => 'Промокод «{p}» уже занят.',
            'err.email_invalid' => 'Укажите корректный email.',
            'err.email_dup' => 'Этот email уже зарегистрирован в программе.',
            'err.name_required' => 'Укажите ваше имя.',
            'err.min_socials' => 'Добавьте минимум 2 соцсети.',
            'err.over_limit' => 'Скидка ({d}%) + кешбек ({c}%) превышают лимит {l}%.',
            'err.no_blogger' => 'Не указан блогер.',
            'err.not_found' => 'Блогер не найден в системе.',
            'err.generic' => 'Что-то пошло не так. Попробуйте позже.',
        ],
        'vi' => [
            'lang' => 'VI',
            'w.eyebrow' => 'Chương trình cho influencer',
            'w.title' => 'Mời khách —<br>nhận thưởng cùng <i>Veranda</i>',
            'w.lead' => 'Mã khuyến mãi riêng, hoàn tiền mỗi lượt ghé và báo cáo minh bạch trong một màn hình. Không gọi điện, không bảng tính thủ công.',
            'w.perk1.t' => 'Mã khuyến mãi riêng của bạn',
            'w.perk1.d' => 'Khách đọc mã tại quầy và được giảm giá. Lượt ghé tự động được tính cho bạn.',
            'w.perk2.t' => 'Hoàn tiền trên mỗi hóa đơn',
            'w.perk2.d' => 'Bạn nhận phần trăm doanh thu của mỗi khách mời. Càng nhiều khách — thu nhập càng cao.',
            'w.perk3.t' => 'Hoàn toàn minh bạch',
            'w.perk3.d' => 'Mọi hóa đơn, tiền hoàn tích lũy và các lần chi trả — tất cả trong tài khoản của bạn.',
            'w.limit.badge' => '★ Khởi đầu — 5%',
            'w.limit.title' => 'Phần trăm của bạn hoạt động thế nào',
            'w.limit.p1' => 'Ngay sau khi đăng ký bạn có <b>5%</b> — bạn tự chia giữa <b>giảm giá cho khách</b> và <b>tiền hoàn của bạn</b>. Đủ để bắt đầu kiếm tiền ngay hôm nay.',
            'w.limit.p2' => 'Muốn nhiều hơn? <a class="contact" href="/" target="_blank" rel="noopener">Liên hệ với chúng tôi</a> bằng cách bạn thích — chúng ta sẽ thỏa thuận điều kiện riêng và nâng hạn mức. Thông tin liên hệ có trên trang web và mạng xã hội.',
            'w.have' => 'Đã tham gia cùng chúng tôi?',
            'w.google' => 'Đăng nhập bằng Google',
            'w.divider' => 'thành viên mới',
            'w.reg.h' => 'Đăng ký',
            'w.reg.free' => 'miễn phí',
            'f.name' => 'Tên của bạn',
            'f.name.ph' => 'Anna Ivanova',
            'f.email' => 'Email để đăng nhập Google',
            'f.email.hint' => 'Bạn sẽ dùng nó để vào tài khoản.',
            'f.promo' => 'Mã khuyến mãi',
            'f.promo.hint' => 'Một từ ngắn, không dấu cách — khách đọc tại quầy.',
            'w.socials.h' => 'Mạng xã hội — tối thiểu 2',
            'w.socials.hint' => 'Thêm ít nhất hai — để chúng tôi biết bạn là nhà sáng tạo thật.',
            'w.social.add' => '+ Thêm mạng xã hội',
            'social.choose' => 'Chọn mạng xã hội',
            'social.val.ph' => '@tên hoặc liên kết',
            'social.site' => 'Trang web / khác',
            'social.remove' => 'Bỏ',
            'w.reg.submit' => 'Tạo tài khoản',
            'w.reg.fine' => 'Khi đăng ký, bạn tham gia chương trình Veranda. Hạn mức khởi đầu là 5%, có thể nâng bất cứ lúc nào theo thỏa thuận.',
            'd.who' => 'tài khoản influencer',
            'd.logout' => 'Đăng xuất',
            'd.promo.l' => 'Mã khuyến mãi của bạn',
            'd.promo.sub' => 'Đọc cho khách — giảm giá áp dụng tại quầy',
            'd.period.from' => 'Từ ngày',
            'd.period.to' => 'Đến ngày',
            'd.period.btn' => 'Xem kỳ',
            'd.payout' => 'Cần chi trả',
            'd.payout.meta' => 'Tích lũy {a} ₫ · đã trả {p} ₫',
            'd.stat.checks' => 'Hóa đơn',
            'd.stat.revenue' => 'Doanh thu',
            'd.stat.accrued' => 'Tích lũy',
            'd.stat.paid' => 'Đã trả',
            'd.checks.h' => 'Hóa đơn trong kỳ',
            'd.checks.empty' => 'Chưa có hóa đơn — hãy chia sẻ mã của bạn 😉',
            'd.tbl.date' => 'Ngày',
            'd.tbl.sum' => 'Tổng ₫',
            'd.tbl.disc' => 'Giảm ₫',
            'd.socials.h' => 'Mạng xã hội của bạn',
            'd.dist.h' => 'Mã và phân bổ',
            'd.limit.l' => 'Hạn mức của bạn<br>giảm giá + hoàn tiền',
            'd.f.promo' => 'Mã khuyến mãi',
            'd.f.disc' => 'Giảm giá cho khách, %',
            'd.f.cash' => 'Hoàn tiền của bạn, %',
            'd.hint.tpl' => 'Tổng {s}% trên {l}% khả dụng',
            'd.save' => 'Lưu',
            'd.raise.start' => 'Muốn hơn 5%? <a href="/" target="_blank" rel="noopener">Liên hệ với chúng tôi</a> — bàn điều kiện và nâng hạn mức. Liên hệ trên trang web.',
            'd.raise.more' => 'Cần hạn mức cao hơn? <a href="/" target="_blank" rel="noopener">Nhắn cho chúng tôi</a> — luôn sẵn sàng.',
            'd.foot' => 'Tiền hoàn tính trên doanh thu sau giảm giá. Chi trả theo thỏa thuận.',
            'd.load.err' => 'Không tải được dữ liệu. Vui lòng thử lại sau.',
            'fl.reg.ok' => 'Xong! Đăng nhập Google bằng chính email đó — tài khoản của bạn đã sẵn sàng.',
            'fl.csrf' => 'Phiên đã hết hạn — tải lại trang và thử lại.',
            'fl.throttle' => 'Quá nhiều lần thử. Vui lòng đợi một chút rồi thử lại.',
            'fl.hp' => 'Không gửi được. Vui lòng thử lại sau.',
            'fl.saved' => 'Đã lưu thay đổi.',
            'fl.save.csrf' => 'Phiên đã hết hạn — tải lại trang và lưu lại.',
            'err.promocode_empty' => 'Mã khuyến mãi không được để trống.',
            'err.promocode_space' => 'Mã khuyến mãi không được có dấu cách (gõ tại quầy).',
            'err.promocode_long' => 'Mã khuyến mãi quá dài (tối đa 50 ký tự).',
            'err.promocode_dup' => 'Mã “{p}” đã có người dùng.',
            'err.email_invalid' => 'Vui lòng nhập email hợp lệ.',
            'err.email_dup' => 'Email này đã đăng ký trong chương trình.',
            'err.name_required' => 'Vui lòng nhập tên của bạn.',
            'err.min_socials' => 'Thêm ít nhất 2 mạng xã hội.',
            'err.over_limit' => 'Giảm giá ({d}%) + hoàn tiền ({c}%) vượt hạn mức {l}%.',
            'err.no_blogger' => 'Chưa chỉ định influencer.',
            'err.not_found' => 'Không tìm thấy influencer.',
            'err.generic' => 'Đã có lỗi. Vui lòng thử lại sau.',
        ],
    ];
}
